### ISSUE TITLE
https://scancode-licensedb.aboutcode.org/wxwindows.LICENSE is empty

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-licensedb#21] opened 2022-09-08 20:02 UTC
I would expect the text of the (deprecated) [wxWindows license](https://spdx.org/licenses/wxWindows.html) to be downloadable from https://scancode-licensedb.aboutcode.org/wxwindows.LICENSE, but the return file is empty.

**Comment by sschuberth** [comment] 2022-09-08 20:03
The same is true for https://scancode-licensedb.aboutcode.org/gpl-2.0-classpath.LICENSE.

**Comment by AyanSinhaMahapatra** [comment] 2022-09-09 18:22
There are 3 cases where scancode licenses has a .yml file but not a .LICENSE file:

1. is_deprecated: True example: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/wxwindows.yml#L2
2. is_generic: True example: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/proprietary.yml#L8
3. is_unknown: True example: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unknown-license-reference.yml#L6

There are some mistakes i.e. some file that don't have the .LICENSE file, but aren't tagged like one of these correctly. They should be.

**Comment by sschuberth** [comment] 2022-09-09 20:51
I do get why for cases 2. and 3. no concrete license text can be determined. But why also for 1.? I'd expect to basically get the same as https://github.com/spdx/license-list-data/blob/v3.18/text/deprecated_wxWindows.txt.

**Comment by pombredanne** [comment] 2022-09-11 17:49
@sschuberth It is mostly harmless to add these texts back if you think there is a need for these. 

These  two have long been gone.

- https://github.com/nexB/scancode-toolkit/commit/13696592468888811867a32851c9742cd813d615#diff-8e097d89389273731310e8873f36e95ba1e36ca1d8de2e65201d477980017394 renamed this to use as a rule when the license went deprecated

- https://github.com/nexB/scancode-toolkit/commit/fd97820d0098fd777bbf102c7dd6ba9741efd438 was deleted for the same reason

There used to be a time when a deprecated text could not exist as a duplicate of anything else. And we still wanted to detected deprecated... That's not an issue nowadays.

**Comment by sschuberth** [comment] 2022-09-11 18:42
> @sschuberth It is mostly harmless to add these texts back if you think there is a need for these.

ORT is using ScanCode as the primary source for SPDX license text (as upstream SPDX license text are still formatted oddly), so it would simply be nice to really get the ttext for *aaL* licenses (incl. deprecated ones) from ScanCode. Otherwise we have to use code like [this](https://github.com/oss-review-toolkit/ort/pull/5770/commits/44d6d560c540441a2b324eb492b3ffc48abde137#diff-2b2d0e698d405fc5b02de270fa4555d7f0c1692b6a2f601eb50776754802cc26R88-R89).

**Comment by pombredanne** [comment] 2023-01-16 12:10
This has been fixed and merged

**Closed by pombredanne** 2023-01-16 12:10 UTC
