### ISSUE TITLE
Add Xceed Community license

### ISSUE THREAD

**Issue by AJDurant** [nexB/scancode-licensedb#20] opened 2022-04-22 15:05 UTC
https://github.com/xceedsoftware/wpftoolkit/blob/master/license.md

**Comment by pombredanne** [comment] 2022-04-22 15:08
@AJDurant Thanks!

**Comment by pombredanne** [comment] 2022-04-22 15:11
@DennisClark FYI

**Comment by pombredanne** [comment] 2022-04-22 15:14
This is a notice example https://github.com/xceedsoftware/wpftoolkit/blob/5a8bbe7895792f6cd7fa6a76b77f9330e996d6a6/ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/Utils/Exceptions/ThrowException.cs

@XceedBoucherS FYI the plan is to include this in the licensedb and can detect this with ScanCode toolkit. I assume there is no objection since this is a public document

**Comment by pombredanne** [comment] 2022-04-22 20:57
@XceedBoucherS The licenseDB is a database of mostly all licenses and is published at https://scancode-licensedb.aboutcode.org/

And this is stored in and used by ScanCode-toolkit (which I like to think as the industry open source license detection tool) to detect license texts and notices  as seen in code. 

The actual licensedb data are stored there https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses
Scancode Toolkit is at https://github.com/nexB/scancode-toolkit and the web app project based on and using ScanCode toolkit is at http//scancode.io and https://github.com/nexB/scancode.io/
 
The issue is a request by @AJDurant  to add your Xceed Community license to the LicenseDB. I want to make sure that there is no objection on your side since you published this. This would mean that folks using your code would be able to detect that your code is under your license and therefore comply more efficiently with your license terms.

**Comment by XceedBoucherS** [comment] 2022-04-25 11:31
Hi @pombredanne ,
Thank you for the explanation.
No, there are no objection to add the Xceed Community license to the LicenseDB. You can add it.
Thank you

**Comment by AyanSinhaMahapatra** [comment] 2022-09-09 18:23
https://scancode-licensedb.aboutcode.org/xceed-community-2021.html is there now.

**Comment by pombredanne** [comment] 2022-09-11 09:38
Closing now.

**Closed by pombredanne** 2022-09-11 09:38 UTC
