### ISSUE TITLE
License updates from scancode not working as intended

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-licensedb#32] opened 2023-03-08 11:35 UTC
During a license text import in [ORT](https://github.com/oss-review-toolkit/ort), I noticed that the following `LICENSE` files seem to be missing:

https://scancode-licensedb.aboutcode.org/adacore-doc.LICENSE
https://scancode-licensedb.aboutcode.org/bsd-advertising-acknowledgement.LICENSE
https://scancode-licensedb.aboutcode.org/cc-by-nc-sa-2.0-de.LICENSE
https://scancode-licensedb.aboutcode.org/cfitsio.LICENSE
https://scancode-licensedb.aboutcode.org/cornell-lossless-jpeg.LICENSE
https://scancode-licensedb.aboutcode.org/hpnd-export-us.LICENSE
https://scancode-licensedb.aboutcode.org/hpnd-sell-variant-mit-disclaimer.LICENSE
https://scancode-licensedb.aboutcode.org/iec-code-components-eula.LICENSE
https://scancode-licensedb.aboutcode.org/ijg-short.LICENSE
https://scancode-licensedb.aboutcode.org/jpl-image.LICENSE
https://scancode-licensedb.aboutcode.org/kazlib.LICENSE
https://scancode-licensedb.aboutcode.org/loop.LICENSE
https://scancode-licensedb.aboutcode.org/offis.LICENSE
https://scancode-licensedb.aboutcode.org/qpl-1.0-inria-2004.LICENSE
https://scancode-licensedb.aboutcode.org/symlinks.LICENSE
https://scancode-licensedb.aboutcode.org/tpdl.LICENSE
https://scancode-licensedb.aboutcode.org/ttwl.LICENSE
https://scancode-licensedb.aboutcode.org/ucar.LICENSE
https://scancode-licensedb.aboutcode.org/w3m.LICENSE

**Comment by AyanSinhaMahapatra** [comment] 2023-03-08 11:42
@sschuberth weird, looks like the CI job did not work as intended :thinking: looking into this

**Comment by AyanSinhaMahapatra** [comment] 2023-03-08 12:57
@sschuberth Btw also
>During a license text import in [ORT](https://github.com/oss-review-toolkit/ort), I noticed that the following LICENSE files seem to be missing

How do you perform this import (is there a script in ORT you can point me to), and do you think using the scancode command directly to generate the licensedb and dump all the data (as API) is better than using scancode-licensedb.org? See https://github.com/nexB/scancode-toolkit/issues/2738 btw, which is why the command was added to scancode-toolkit.

**Comment by AyanSinhaMahapatra** [comment] 2023-03-08 13:25
Thanks for explaining @sschuberth :+1:

**Comment by armijnhemel** [comment] 2023-06-07 17:16
Is this the reason why I am seeing for example:

```
Showing 2,147 changed files with 2,147 additions and 2,147 deletions.
```

in Git commits (for example: https://github.com/nexB/scancode-licensedb/commit/355f106b19006e779c5002ac7ed17c1361c52544 )?

It seems that the only thing that is updated is the version number. Adding @pombredanne

**Comment by AyanSinhaMahapatra** [comment] 2023-06-07 17:42
@armijnhemel no, that issue is tracked in https://github.com/nexB/scancode-licensedb/issues/31, this issue was fixed by the PR above.

**Closed** 2023-06-07 21:33 UTC
